Repository techly-africa/Auth-x, pull requests merged in 2023-10, with the labels that each got.

#5 feat(auth):Implement email verification endpoint
  .env.example
  dist/app.controller.d.ts
  dist/app.controller.js
  dist/app.controller.js.map
  dist/app.module.d.ts
  dist/app.module.js
  dist/app.module.js.map
  dist/app.service.d.ts
  dist/app.service.js
  dist/app.service.js.map
  dist/main.d.ts
  dist/main.js
  dist/main.js.map
  dist/tsconfig.build.tsbuildinfo
  dist/user/dto/create-user.dto.d.ts
  dist/user/dto/create-user.dto.js
  dist/user/dto/create-user.dto.js.map
  dist/user/dto/update-user.dto.d.ts
  dist/user/dto/update-user.dto.js
  dist/user/dto/update-user.dto.js.map
  dist/user/schemas/user.schema.d.ts
  dist/user/schemas/user.schema.js
  dist/user/schemas/user.schema.js.map
  dist/user/user.controller.d.ts
  dist/user/user.controller.js
  dist/user/user.controller.js.map
  dist/user/user.module.d.ts
  dist/user/user.module.js
  dist/user/user.module.js.map
  dist/user/user.service.d.ts
  dist/user/user.service.js
  dist/user/user.service.js.map
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/mail/mail.module.ts
  src/mail/mail.service.ts
  src/user/dto/create-user.dto.ts
  src/user/schemas/user.schema.ts
  src/user/user.controller.spec.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: Ready for Merge

#8 feat: Create Role Management System
  src/app.controller.ts
  src/app.module.ts
  src/auth/Guards/admin.guard.ts
  src/auth/Guards/user.guard.ts
  src/auth/Guards/vendor.guard.ts
  src/auth/Validations/login-user-validation.pipe.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/login-user.dto.ts
  src/mail/mail.module.ts
  src/mail/mail.service.ts
  src/permission/permission.controller.ts
  src/role/dto/create-role.dto.ts
  src/role/entities/role.entity.ts
  src/role/role.controller.ts
  src/role/role.module.ts
  src/role/role.service.ts
  src/role/schemas/role.schema.ts
  src/role_permission/dto/create-role_permission.dto.ts
  src/role_permission/dto/update-role_permission.dto.ts
  src/role_permission/entities/role_permission.entity.ts
  src/role_permission/role_permission.controller.ts
  src/role_permission/role_permission.module.ts
  src/role_permission/role_permission.service.ts
  src/role_permission/schemas/role_permision.schema.ts
  src/user/dto/create-user.dto.ts
  src/user/schemas/user.schema.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  src/user_role/dto/create-user_role.dto.ts
  src/user_role/dto/update-user_role.dto.ts
  src/user_role/entities/user_role.entity.ts
  src/user_role/schemas/user_role.schema.ts
  src/user_role/user_role.controller.ts
  src/user_role/user_role.module.ts
  src/user_role/user_role.service.ts
Labels: Ready for Merge

#9 Enhancement: Comprehensive Permission Management(RBAC)
  README.md
  src/app.controller.ts
  src/auth/auth.service.ts
  src/main.ts
  src/permission/DTO/create-perm.dto.ts
  src/permission/DTO/update-perm.dto.ts
  src/permission/dto/create-permission.dto.ts
  src/permission/dto/update-permission.dto.ts
  src/permission/entities/permission.entity.ts
  src/permission/permission.controller.ts
  src/permission/permission.module.ts
  src/permission/permission.service.ts
  src/permission/schemas/permission.schema.ts
  src/role/dto/assign-perm.dto.ts
  src/role/role.controller.ts
  src/role/role.module.ts
  src/role/role.service.ts
  src/role/schemas/role.schema.ts
  src/user/schemas/user.schema.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: Ready for Reviews

#10 feat: adding user service tests
  .github/workflows/QA.yaml
  README.md
  package-lock.json
  package.json
  src/auth/auth.controller.spec.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/mail/mail.service.spec.ts
  src/permission/permission.controller.spec.ts
  src/permission/permission.service.spec.ts
  src/permission/permission.service.ts
  src/role/role.controller.spec.ts
  src/role/role.service.spec.ts
  src/role/role.service.ts
  src/user/user.controller.spec.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: Ready for Reviews

#13 feat: Add role-based access control middlewares
  src/auth/Guards/role.guard.ts
  src/auth/auth.service.ts
  src/role/role.controller.ts
  src/role/role.module.ts
  src/user/schemas/user.schema.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: Work in Progress

#14 feat: raising coverage
  package.json
  src/auth/Guards/admin.guard.spec.ts
  src/auth/Guards/admin.guard.ts
  src/auth/Guards/role.guard.spec.ts
  src/auth/Guards/role.guard.ts
  src/auth/Guards/user.guard.spec.ts
  src/auth/Guards/user.guard.ts
  src/auth/Guards/vendor.guard.spec.ts
  src/auth/Guards/vendor.guard.ts
  src/user/stubs/create-user.dto.stub.ts
  src/user/user.controller.ts
  src/user/user.service.spec.ts
Labels: Ready for Reviews

#17 Update Deletion Functionality
  .github/pull_request_template.md
  package-lock.json
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/login-user.dto.ts
  src/mail/mail.service.ts
  src/permission/permission.controller.ts
  src/permission/permission.service.ts
  src/permission/schemas/permission.schema.ts
  src/role/role.controller.ts
  src/role/role.service.ts
  src/role/schemas/role.schema.ts
  src/user/schemas/user.schema.ts
  src/user/user.controller.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: Work in Progress

#19 Adding Social Login Integration with Google, GitHub, and Facebook
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/Strategies/facebook.strategy.ts
  src/auth/Strategies/github.strategy.ts
  src/auth/Strategies/google.strategy.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
Labels: Ready for Reviews

#20 feat:adding 2Fa
  package-lock.json
  package.json
  src/auth/Guards/role.guard.spec.ts
  src/auth/Guards/role.guard.ts
  src/auth/Guards/user.guard.ts
  src/auth/Strategies/google.strategy.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/mail/mail.service.ts
  src/main.ts
  src/permission/permission.service.spec.ts
  src/role/role.service.spec.ts
  src/user/dto/create-user.dto.ts
  src/user/schemas/user.schema.ts
  src/user/user.controller.spec.ts
  src/user/user.controller.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
  src/user/utils/codeGenerator.spec.ts
  src/user/utils/codeGenerator.ts
  src/user/utils/dateUtility.spec.ts
  src/user/utils/dateUtility.ts
Labels: Ready for Reviews

#22 Feature/app service env variable
  package-lock.json
  src/app.controller.spec.ts
  src/app.service.ts
  src/mail/mail.service.spec.ts
  src/mail/mail.service.ts
  src/user/utils/dateUtility.spec.ts
Labels: Ready for Reviews
